---
apiVersion: v1
kind: Service
metadata:
  name: rd-elasticsearch
  labels:
    k8s-app: rd-elasticsearch
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
    - port: 9200
      protocol: TCP
      targetPort: es-http
  selector:
    k8s-app: rd-elasticsearch